repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.11.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@9.11.1
          - eslint-config-standard@17.1.0
          - eslint-plugin-import@2.29.1
          - eslint-plugin-n@16.6.2
          - eslint-plugin-promise@6.4.0
        files: \.(js|jsx|ts|tsx)$
