version: '3.9'
services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CORS_ALLOW_ALL: ${CORS_ALLOW_ALL}
      REDIS_URL: ${REDIS_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      EXPORTS_ASYNC: ${EXPORTS_ASYNC}
    volumes:
  - media:/app/media
  - backups:/backups
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request;import sys;\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\ntry:\n urllib.request.urlopen('http://localhost:8000/healthz', timeout=3)\n sys.exit(0)\nexcept Exception:\n sys.exit(1)"]
      interval: 15s
      timeout: 5s
      retries: 10
  web:
    working_dir: /app/web
    image: node:20-alpine
    command: sh -c "npm ci && npm run dev"
    volumes:
      - .:/app
    ports:
      - "5174:5174"
    depends_on:
      - api
  worker:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: bash -c "celery -A app.celery:app worker -l info"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_URL: ${REDIS_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      EXPORTS_ASYNC: ${EXPORTS_ASYNC}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  beat:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: bash -c "while true; do python manage.py enforce_subscription_periods; sleep 86400; done"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_URL: ${REDIS_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      EXPORTS_ASYNC: ${EXPORTS_ASYNC}
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_healthy
  backup:
    image: alpine:3.20
    # Install postgresql-client and run daily dump to /backups
    entrypoint: sh -c "apk add --no-cache postgresql15-client >/dev/null && sleep 10 && while true; do /app/scripts/pg_dump_daily.sh; sleep 86400; done"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - backups:/backups
      - .:/app:ro
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
  media:
  backups: