version: '3.9'
services:
  api:
    environment:
      DEBUG: '1'
      ALLOWED_HOSTS: localhost,127.0.0.1
    ports:
      - "8000:8000"
  web:
    ports:
      - "5173:5173"
  db:
    ports:
      - "5432:5432"