# Generated by GitHub Copilot on 2025-08-28
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("plan", "plan"), ("write", "write"), ("revise", "revise"), ("format", "format")], max_length=16)),
                ("model_id", models.CharField(blank=True, default="", max_length=64)),
                ("duration_ms", models.IntegerField(default=0)),
                ("tokens_used", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_text", models.TextField(blank=True, default="")),
                ("org_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
