# Generated by Django 5.0.7 on 2025-09-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aimemory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aimemory',
            new_name='ai_aimemory_org_id_c0a075_idx',
            old_name='ai_mem_org_section_idx',
        ),
        migrations.RenameIndex(
            model_name='aimemory',
            new_name='ai_aimemory_created_c55f40_idx',
            old_name='ai_mem_user_section_idx',
        ),
    ]
