# Generated by Django 5.0.7 on 2025-09-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_backfill_aichunk_embeddings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aichunk',
            new_name='ai_aichunk_resourc_1c8a69_idx',
            old_name='ai_aichunk_resource_id_idx',
        ),
        migrations.RenameIndex(
            model_name='aichunk',
            new_name='ai_aichunk_embeddi_f6e0d4_idx',
            old_name='ai_aichunk_embedding__idx',
        ),
        migrations.RenameIndex(
            model_name='aijobcontext',
            new_name='ai_aijobcon_created_6f8f2e_idx',
            old_name='ai_aijobcon_created__idx',
        ),
        migrations.RenameIndex(
            model_name='aijobcontext',
            new_name='ai_aijobcon_job_id_fcaa17_idx',
            old_name='ai_aijobcon_job_id_idx',
        ),
        migrations.RenameIndex(
            model_name='aiprompttemplate',
            new_name='ai_aiprompt_role_d2e1ff_idx',
            old_name='ai_aiprompt_role_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='airesource',
            new_name='ai_airesour_type_4368d5_idx',
            old_name='ai_airesour_type_9d1e1c_idx',
        ),
        migrations.RenameIndex(
            model_name='airesource',
            new_name='ai_airesour_created_3b00dc_idx',
            old_name='ai_airesour_created__idx',
        ),
    ]
