# Generated by Django 5.0.7 on 2025-09-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_rename_ai_aichunk_resource_id_idx_ai_aichunk_resourc_1c8a69_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijobcontext',
            name='redaction_map',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='aijobcontext',
            name='template_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aiprompttemplate',
            name='blueprint_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiprompttemplate',
            name='blueprint_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aimetric',
            name='type',
            field=models.CharField(choices=[('plan', 'plan'), ('write', 'write'), ('revise', 'revise'), ('format', 'format'), ('promote', 'promote')], max_length=16),
        ),
    ]
