# Generated by Django 5.0.7 on 2025-08-28 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orgs', '0002_orginvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orginvite',
            new_name='orgs_orginv_org_id_f879b0_idx',
            old_name='org_email_idx',
        ),
    ]
