# Generated by Django 5.0.7 on 2025-08-28 13:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orgs', '0003_rename_org_email_idx_orgs_orginv_org_id_f879b0_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgProposalAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=datetime.date.today)),
                ('allocation', models.IntegerField(default=0)),
                (
                    'admin',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='org_allocations', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'org',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='admin_allocations', to='orgs.organization'
                    ),
                ),
            ],
            options={
                'unique_together': {('admin', 'org', 'month')},
            },
        ),
    ]
