# Generated by Django 5.0.7 on 2025-09-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_orginvite_expires_at'),
        ('proposals', '0003_require_org_on_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='orgs.organization'),
        ),
    ]
