/** AUTO-GENERATED: DO NOT EDIT. Source: locales/en.yml */
export const KEYS = {
  'ai.revise.locked': "Section is locked. Unlock before revising.",
  'billing.checkout.success_title': "Subscription active",
  'errors.account.invalid_email': "Please enter a valid email address.",
  'errors.account.invalid_username': "Username must be 2-64 chars (letters, numbers, _ . -).",
  'errors.account.no_changes': "Make a change before saving.",
  'errors.account.username_taken': "That username is already taken.",
  'errors.ai.not_found': "Requested resource not found.",
  'errors.ai.quota_daily_reached': "Daily AI request limit reached. Try again later.",
  'errors.ai.quota_monthly_tokens_reached': "Monthly AI token allotment exhausted.",
  'errors.ai.rate_limited': "You're making requests too fast. Please wait {retry_after}s.",
  'errors.generic.unexpected': "Something went wrong. Please try again.",
  'errors.revision.cap_reached': "You've reached the revision limit ({count}/{limit}).",
  'ui.account.buttons.save': "Save",
  'ui.account.heading': "Account",
  'ui.account.labels.email': "Email",
  'ui.account.labels.first_name': "First name",
  'ui.account.labels.last_name': "Last name",
  'ui.account.labels.username': "Username",
  'ui.account.status.saved': "Saved",
  'ui.auth.app_name': "Granterstellar",
  'ui.auth.choose_plan': "Choose a plan",
  'ui.auth.confirmation_stub': "Confirmation email sent to your address (stub). Name: {name}",
  'ui.auth.continue_button': "Continue",
  'ui.auth.create_account_button': "Create an account",
  'ui.auth.debug_email_placeholder': "debug: you@example.com",
  'ui.auth.debug_google_button': "Debug Google Login",
  'ui.auth.debug_oauth_failed': "Debug OAuth failed",
  'ui.auth.enter_email_debug_oauth': "Enter email for debug OAuth",
  'ui.auth.invite_accept_button': "Accept invite",
  'ui.auth.invite_accept_failed_prefix': "Invite accept failed:",
  'ui.auth.invite_accept_pending_button': "Accept pending invite",
  'ui.auth.invite_accept_success': "Invite accepted",
  'ui.auth.invite_banner_detected': "Organization invite detected.",
  'ui.auth.invite_not_now_button': "Not now",
  'ui.auth.invite_token_placeholder': "Invite token (optional)",
  'ui.auth.login_button': "Login",
  'ui.auth.login_heading': "Login",
  'ui.auth.name_placeholder': "Your name",
  'ui.auth.org_name_placeholder': "Organization name (or leave blank if using an invite)",
  'ui.auth.password_placeholder': "password",
  'ui.auth.plan_enterprise': "Enterprise",
  'ui.auth.plan_free': "Free",
  'ui.auth.plan_pro': "Pro",
  'ui.auth.registration_failed_prefix': "Registration failed:",
  'ui.auth.registration_heading': "Complete your registration",
  'ui.auth.sign_in_facebook': "Sign in with Facebook",
  'ui.auth.sign_in_failed_generic': "Sign-in failed. Please try again.",
  'ui.auth.sign_in_github': "Sign in with GitHub",
  'ui.auth.sign_in_google': "Sign in with Google",
  'ui.auth.signing_in': "Signing you in…",
  'ui.auth.username_placeholder': "username",
  'ui.author_panel.approve_save_button': "Approve & Save",
  'ui.author_panel.approved_sections': "Approved sections",
  'ui.author_panel.attach_files_label': "Attach files (pdf, docx, txt, images)",
  'ui.author_panel.author_label': "Author",
  'ui.author_panel.by_user': " by {username}",
  'ui.author_panel.change_request_placeholder': "Change request (optional)",
  'ui.author_panel.created_label': "Created",
  'ui.author_panel.draft_label': "Draft",
  'ui.author_panel.errors.final_format_failed': "Final format failed",
  'ui.author_panel.errors.plan_load_failed': "Failed to load plan",
  'ui.author_panel.errors.revise_failed': "Revise failed",
  'ui.author_panel.errors.save_failed': "Save failed",
  'ui.author_panel.errors.save_note_failed': "Save note failed",
  'ui.author_panel.errors.write_failed': "Write failed",
  'ui.author_panel.files_for_section': "Files for this section",
  'ui.author_panel.final_formatting_heading': "Final formatting (runs after all sections are approved)",
  'ui.author_panel.formatted_preview': "Formatted preview",
  'ui.author_panel.grant_url_placeholder': "Grant URL (optional)",
  'ui.author_panel.internal_note_label': "Internal note",
  'ui.author_panel.just_now': " (just now)",
  'ui.author_panel.last_edited_label': "Last edited",
  'ui.author_panel.last_saved': "Last saved {time}",
  'ui.author_panel.note_placeholder': "Add a note for collaborators",
  'ui.author_panel.ocr_preview': "OCR preview",
  'ui.author_panel.plan_proposal_heading': "Plan your proposal",
  'ui.author_panel.previous_label': "Previous",
  'ui.author_panel.revise_button': "Revise",
  'ui.author_panel.run_final_formatting': "Run Final Formatting",
  'ui.author_panel.save_note_button': "Save Note",
  'ui.author_panel.schema_label': "Schema: {version}",
  'ui.author_panel.section_counter': "Section {current} / {total}:",
  'ui.author_panel.spec_placeholder': "Or paste a brief specification (optional)",
  'ui.author_panel.start_button': "Start",
  'ui.author_panel.template_hint_placeholder': "Template hint (optional)",
  'ui.author_panel.untitled': "Untitled",
  'ui.author_panel.upload_failed': "Upload failed",
  'ui.author_panel.uploading': "Uploading…",
  'ui.author_panel.working': "Working…",
  'ui.author_panel.write_button': "Write",
  'ui.billing.heading': "Billing",
  'ui.buttons.approve_save': "Approve & Save",
  'ui.buttons.archive': "Archive",
  'ui.buttons.close_author': "Close Author",
  'ui.buttons.export': "Export",
  'ui.buttons.open_author': "Open Author",
  'ui.buttons.revise': "Revise",
  'ui.buttons.run_final_formatting': "Run Final Formatting",
  'ui.buttons.save_note': "Save Note",
  'ui.buttons.start': "Start",
  'ui.buttons.unarchive': "Unarchive",
  'ui.buttons.write': "Write",
  'ui.cancel_at_period_end_flag': "Cancel at period end: yes",
  'ui.common.files_for_section': "Files for this section",
  'ui.common.loading': "Loading…",
  'ui.common.ocr_preview': "OCR preview",
  'ui.common.untitled': "Untitled",
  'ui.common.upload_failed': "Upload failed",
  'ui.common.uploading': "Uploading…",
  'ui.common.working': "Working…",
  'ui.coupon_label': "Coupon/Promotion code (optional):",
  'ui.coupon_placeholder': "SUMMER100",
  'ui.dashboard.active_count': "Active: {count}",
  'ui.dashboard.archive_button': "Archive",
  'ui.dashboard.billing_portal_button': "Billing Portal",
  'ui.dashboard.cancel_at_period_end_button': "Cancel at period end",
  'ui.dashboard.checkout_unavailable': "Checkout unavailable",
  'ui.dashboard.close_author': "Close Author",
  'ui.dashboard.created_this_month': "Created this month: {count}/{limit}",
  'ui.dashboard.export_button': "Export",
  'ui.dashboard.export_failed': "Export failed: {message}",
  'ui.dashboard.export_still_processing': "Export still processing; try again later",
  'ui.dashboard.exporting': "Exporting…",
  'ui.dashboard.format_docx': "DOCX",
  'ui.dashboard.format_md': "Markdown",
  'ui.dashboard.format_pdf': "PDF",
  'ui.dashboard.heading': "My Proposals",
  'ui.dashboard.loading': "Loading…",
  'ui.dashboard.new_blocked': "New proposal blocked: {reason}",
  'ui.dashboard.new_button': "New",
  'ui.dashboard.open_author': "Open Author",
  'ui.dashboard.org_id_placeholder': "Org ID (optional)",
  'ui.dashboard.paid_required_to_archive': "Paid plan required to archive",
  'ui.dashboard.paywall_alert': "Paywall: {reason}. Click Upgrade to continue.",
  'ui.dashboard.period_ends': "Period ends: {date}",
  'ui.dashboard.portal_unavailable': "Portal unavailable",
  'ui.dashboard.promo_active': "Promo: {discount}",
  'ui.dashboard.proposal_id_prefix': "#",
  'ui.dashboard.resume_button': "Resume",
  'ui.dashboard.state_archived': "archived",
  'ui.dashboard.state_draft': "draft",
  'ui.dashboard.subscription_cancelled_schedule': "Subscription will cancel at period end.",
  'ui.dashboard.subscription_resumed': "Subscription resumed.",
  'ui.dashboard.tier_status': "Tier: {tier} · Status: {status}",
  'ui.dashboard.unarchive_button': "Unarchive",
  'ui.dashboard.untitled': "Untitled",
  'ui.dashboard.upgrade_button': "Upgrade",
  'ui.diff.draft': "Draft",
  'ui.diff.heading': "Changes",
  'ui.diff.previous': "Previous",
  'ui.errors.billing.cancel_failed': "Cancel failed",
  'ui.errors.billing.resume_failed': "Resume failed",
  'ui.errors.export_failed': "Export failed",
  'ui.errors.export_still_processing': "Export still processing; try again later",
  'ui.errors.final_format_failed': "Final format failed",
  'ui.errors.plan_load_failed': "Failed to load plan",
  'ui.errors.revise_failed': "Revise failed",
  'ui.errors.save_failed': "Save failed",
  'ui.errors.save_note_failed': "Save note failed",
  'ui.errors.write_failed': "Write failed",
  'ui.labels.approved_sections': "Approved sections",
  'ui.labels.attach_files': "Attach files (pdf, docx, txt, images)",
  'ui.labels.author': "Author",
  'ui.labels.change_request_optional': "Change request (optional)",
  'ui.labels.created': "Created",
  'ui.labels.final_formatting_intro': "Final formatting (runs after all sections are approved)",
  'ui.labels.formatted_preview': "Formatted preview",
  'ui.labels.grant_url_optional': "Grant URL (optional)",
  'ui.labels.internal_note': "Internal note",
  'ui.labels.last_edited': "Last edited",
  'ui.labels.plan_proposal': "Plan your proposal",
  'ui.labels.section_counter': "Section {current} / {total}:",
  'ui.labels.spec_optional': "Or paste a brief specification (optional)",
  'ui.labels.template_hint_optional': "Template hint (optional)",
  'ui.memory.empty': "No suggestions yet",
  'ui.memory.error': "Failed to load suggestions",
  'ui.memory.heading': "Memory suggestions",
  'ui.memory.insert': "Insert",
  'ui.memory.loading': "Loading…",
  'ui.memory.refresh': "Refresh",
  'ui.memory.uses': "uses: {count}",
  'ui.nav.dashboard': "Dashboard",
  'ui.orgs.accept_invite_button': "Accept invite (paste token)",
  'ui.orgs.accepted': "(accepted)",
  'ui.orgs.confirm_delete': "Delete this organization?",
  'ui.orgs.create_button': "Create",
  'ui.orgs.delete_button': "Delete",
  'ui.orgs.description_placeholder': "Description (optional)",
  'ui.orgs.heading': "Organizations",
  'ui.orgs.hide_button': "Hide",
  'ui.orgs.invite_button': "Invite",
  'ui.orgs.invite_created_token': "Invite created. Token (dev): {token}",
  'ui.orgs.invite_email_placeholder': "name@example.com",
  'ui.orgs.invite_heading': "Invite by email",
  'ui.orgs.joined_org_alert': "Joined organization #{id}",
  'ui.orgs.manage_button': "Manage",
  'ui.orgs.member_role_admin': "admin",
  'ui.orgs.member_role_member': "member",
  'ui.orgs.members_heading': "Members",
  'ui.orgs.new_admin_placeholder': "New admin user ID",
  'ui.orgs.new_name_placeholder': "New org name",
  'ui.orgs.pending': "(pending)",
  'ui.orgs.pending_invites_heading': "Pending invites",
  'ui.orgs.revoke_button': "Revoke",
  'ui.orgs.revoked': "(revoked)",
  'ui.orgs.token_label': "token: {value}",
  'ui.orgs.transfer_button': "Transfer",
  'ui.orgs.transfer_heading': "Transfer ownership",
  'ui.orgs.use_button': "Use",
  'ui.paywall.reasons.active_cap_reached': "Active proposal cap reached for your plan",
  'ui.paywall.reasons.monthly_cap_reached': "Monthly creation limit reached",
  'ui.paywall.reasons.ok': "OK",
  'ui.paywall.reasons.quota': "Quota reached",
  'ui.price_id_label': "Price ID (optional):",
  'ui.price_id_placeholder': "price_123... (test)",
  'ui.proposals_ui.last_saved': "Last saved {time}",
  'ui.proposals_ui.schema': "Schema: {version}",
  'ui.proposals.empty_state': "No proposals yet",
  'ui.seats_label': "Seats (quantity):",
  'ui.seats_line': "Seats: {count}",
} as const;

export type Key = keyof typeof KEYS;

/**
 * Translate a key. If the key is unexpectedly missing (should not happen if generated),
 * returns the key string itself to avoid runtime crashes.
 * Supports simple {placeholder} interpolation.
 */
export function t(key: Key | string, params?: Record<string, string | number>): string {
  if (!(key in KEYS)) return String(key);
  let msg = KEYS[key as Key];
  if (!params) return msg;
  return msg.replace(/\{(\w+)\}/g, (_, p) => (p in params ? String(params[p]) : '{' + p + '}'));
}
