# Generated by Django 5.0.7 on 2025-08-27 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('md', 'Markdown'), ('pdf', 'PDF'), ('docx', 'DOCX')], max_length=8)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='proposals.proposal')),
            ],
        ),
    ]
