name: secret-scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          version: latest
      - name: Run gitleaks (detect)
        id: scan
        run: |
          gitleaks detect --source . --redact --config .gitleaks.toml --report-format sarif --report-path gitleaks.sarif || echo "SCAN_EXIT=$?" >> $GITHUB_ENV
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
      - name: Summarize findings
        run: |
          if grep -q '"rules"' gitleaks.sarif; then
            echo "Potential secrets detected (see SARIF report)." >> $GITHUB_STEP_SUMMARY
          else
            echo "No secrets detected." >> $GITHUB_STEP_SUMMARY
          fi
      - name: Do not fail build on findings (advisory only)
        run: echo "Advisory scan complete"
