name: Web build guards

on:
  pull_request:
    paths:
      - 'web/**'
      - '.github/workflows/web-build-guards.yml'
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/web-build-guards.yml'

jobs:
  build-and-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        working-directory: web
        run: |
          if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm install --no-audit --no-fund; fi
      - name: Build SPA
        working-directory: web
        run: npm run build
      - name: Assert no source maps in dist
        run: |
          if find web/dist -type f -name "*.map" | grep -q .; then
            echo "Error: Source maps found in web/dist" >&2
            find web/dist -type f -name "*.map" >&2
            exit 1
          fi
      - name: Assert no console/debugger strings in dist
        run: |
          if grep -R -E "\bconsole\.|\bdebugger\b" -n web/dist | grep -v -E "LICENSE|license|@license"; then
            echo "Error: console/debugger statements found in dist" >&2
            exit 1
          fi
      - name: Gzip size budget (total JS)
        run: |
          set -euo pipefail
          total=$(find web/dist -type f -name "*.js" -print0 | xargs -0 -I{} sh -c 'gzip -c "{}" | wc -c' | awk '{s+=$1} END{print s+0}')
          echo "Total gzipped JS bytes: $total"
          # Soft budget; adjust as needed in Todo.md
          budget=600000
          if [ "$total" -gt "$budget" ]; then
            echo "Error: total gzipped JS ($total) exceeds budget ($budget)" >&2
            exit 1
          fi
